theme: jekyll-theme-cayman
title: Ruby Anticheat ![https://user-images.githubusercontent.com/110973471/183887863-a727dc59-ba41-40a0-982e-2df761c2b195.png]
description: Free Anticheat for everyone! (Official Ruby AntiCheat)
